spring:
  datasource:
    url: jdbc:postgresql://training-db.cjk8aacizjxv.us-east-1.rds.amazonaws.com:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate